### ISSUE TITLE
SHR CX

### ISSUE THREAD

**Issue by DosWorld** [alexfru/MBiRa#1]
Hi, Alex!

If i am not wrong, 8086 could not execute

shr     cx, 1

because shifts has only two possible form:

shr     ax, 1 ; only ax and onlyl 1
shr     ax, cl ; only ax and only cl

**Comment by alexfru** [comment]
Nope, the shifts aren't limited to AX on 8086/8088. See:

![image](https://user-images.githubusercontent.com/2862502/227745537-65af2562-7fd6-49b2-ba9a-dc9e3552bbbc.png)

![image](https://user-images.githubusercontent.com/2862502/227745590-56575115-b0db-4b25-b79c-436b2e8ca4e1.png)
